apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: TestApp
  template:
    metadata:
      labels:
        app: TestApp
    spec:
      containers:
      - name: testapp
        image: us-central1-docker.pkg.dev/vaibhav-training/myregistery/testapp
        ports:
        - containerPort: 5000
